logiciels/xampp/htdocs/symfony4/my_project_name/src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\PrePersist;
use App\Repository\BookingRepository;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity=Ad::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="la date d'arrivée doit être au bon format")
     * @Assert\GreaterThan("today",message="",groups={"front"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date()
     * @Assert\GreaterThan(propertyPath="startDate",message="")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;
    /**
     * Callback appelé à chaque fois que l'on crée une réservation
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return void
     */

    // Pour le calcul du montant d'une annonce
    public function prePersist(){
        if(empty($this->createdAt)){
            $this->createdAt = new \DateTime();
        }

        if(empty($this->amount)){
            //prix de l'annonce
            $this->amount= $this->ad->getPrice() * $this->getDuration();
        }
    }

    public function isBookableDates(){
        // les dates pas dispo pour une réservation
        $notAvailableDays=$this->ad->getNotAvailableDays();

        // Il faut comparer les dates chosies avec les dates impossible
        $bookingDays=$this->getDays();
        $days=array_map(function($day){
            return $day->format('Y-m-d');
        },$bookingDays);

        $notAvailable=array_map(function($day){
            return $day->format('Y-m-d');
        },$notAvailableDays);

        foreach($days as $day){
            if(array_search($day,$notAvailable)!==false) return false;
        }
        return true;

    }

    /**
     * Permet de récupérer un tableau des journées qui correspondent à ma réservation
     * @return array Taleau des objets DateTime des jours de la réservation
     */
    public function getDays(){

        $resulat=range($this->startDate->getTimestamp(),
        $this->endDate->getTimestamp(),
        24 * 60 * 60);

        $days=array_map(function($dayTimestamp){
            return new \DateTime(date('Y-m-d',$dayTimestamp));
        },$resulat);

        return $days;
    }

    public function getDuration(){
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    //

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

logiciels/xampp/htdocs/symfony4/my_project_name/src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * //@ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 * fields={"email"},
 * message="Un autre utilisateur a cet email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un email valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $picture;

    /**
     * @Assert\EqualTo(propertyPath="hash",message="Fausse confirmation de mot de passe")
     */

    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Ad::class, mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author", orphanRemoval=true)
     */
    private $comments;
  

    public function getFullName(){
        return "{$this->firstName} {$this->lastName}";
    }

   

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return void
     */

    public function initializeSlug()
    {
        if(empty($this->slug))
        {
            $slugify=new Slugify();
            $this->slug=$slugify->slugify($this->firstName.''.$this->lastName);
        }
    }
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    //UserInterface methods 

    public function getRoles(){
        //$roles=$this->userRoles->toArray();
        //dump($roles);

        $roles = $this->userRoles->map(function($role){
            return $role->getTitle();
        })->toArray();
        $roles[]='ROLE_USER';
        //dump($roles)
        return $roles;
    }

    public function getPassword(){
        return $this->hash;
    }

    public function getSalt(){

    }

    public function getUsername(){
        return $this->email;
    }

    public function eraseCredentials(){

    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->removeElement($userRole)) {
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

    

logiciels/xampp/htdocs/symfony4/my_project_name/src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    /**
     * @Route("/ads/{slug}/book", name="booking_create")
     * //@Route("{slug}/book", name="booking_create")
     * //@IsGranted("ROLE_USER")
     */
    public function book(Ad $ad,Request $request,ObjectManager $manager,Booking $booking): Response
    {
        //$booking=new Booking();
        $form=$this->createForm(BookingType::class,$booking);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $user=$this->getUser();
            $booking->setBooker($user)
                    ->setAd($ad);
            // Si les dates ne sont pas dispo, message d'erreur
            if(!$booking->isBookableDates()){
                $this->addFlash(
                    'warning',
                    'Vos dates sont réservées'
                );
            } else{
                $manager->persist($booking);
                $manager->flush();
    
                return $this->redirectToRoute('booking_show',['id'=>$booking->getId(),
                'withAlert'=>true]);
            }
            /*
            $manager->persist($booking);
            $manager->flush();

            return $this->redirectToRoute('booking_show',['id'=>$booking->getId(),
            'withAlert'=>true]); */
        }
        
        return $this->render('booking/index_book.html.twig', [
            'ad'=>$ad,
            'form'=>$form->createView()
        ]);
    }

    /**
     * Permet d'afficher la page d'une réservation
     * @Route("/booking/{id}",name="booking_show")
     * 
     * @param Booking $booking
     * @return Response
     */
    
    public function book_show(Booking $booking,Request $request,ObjectManager $manager){
        $comment=new Comment();
        $form=$this->createForm(CommentType::class,$comment);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $comment->setAd($booking->getAd())
                    ->setAuthor($this->getUser());
            $manager->persist($comment);
        $manager->flush();
        }
        return $this->render('booking/book_show.html.twig',[
            'booking'=>$booking,
            'form'=>$form->createView()
        ]);
    }
}

logiciels/xampp/htdocs/symfony4/my_project_name/templates/booking/book_list.html.twig
{% extends 'base.html.twig' %}

{% block title %} Vos réservations passées {% endblock %}

{% for booking in app.user.bookings %}
    <div class="row mt-5">
        <div class="col-4">
            <img src="{{booking.ad.coverImage}}" class="img-fluid">

            <div class="mt-3">
                {% set comment=ad.commentFromAuthor(app.user) %}
                {% if comment is not null %}
                    <strong> Note donnée:</strong>
                {% else %}
                    Vous n'avez pas encore donné de notes
                {% endif %}
            </div>
        </div>
        <div class="col-8">
            <h4>{{booking.ad.title}}
            <p>
                Reservation <strong> numero {{booking.id}}</strong>
                du {{booking.startDate | date('d:m/Y')}} au 
                {{booking.startDate | date('d:m/Y')}}
            </p>
            <a href="path({{'booking_show',{'id':booking.id})}}" class="btn btn-info">
            plus d'infos</a>
        </div>
    </div>

{% endfor %}

logiciels/xampp/htdocs/symfony4/my_project_name/templates/booking/book_show.html.twig
{% extends 'base.html.twig' %}

{% block title %} Réservation no {{booking.id}}{% endblock %}

{% block body %}
    {% set ad=booking.ad %}
    {% set author=ad.author %}
    <div class="container">
        <h1> Votre réservation (no {{booking.id}})</h1>

        {% if app.request.query.get('withAlert') %}
            <div class="alert alert-success">
                <h4 class="alert-heading"> Bravo ! </h4>
                <p>
                    Votre réservation auprès de 
                    <strong>
                        <a href="{{path('user_show',{'slug':author.slug})}}">{{author.fullName}}</a>
                    </strong> pour l'annonce
                    <strong>
                        <a href="{{path("ads_show",{'slug':ad.slug})}}">{{ad.title}}</a>
                    </strong> a été prise en compte

                </p>
            </div>

        {% endif %}

        <div class="row">
            <div class="col">
                <div class="alert alert-light">
                    <h2>Détails</h2>
                    <dl class="row">
                        <dt class="col-md-4">Numero de la réservation</dt>
                        <dd class="col-md-8">{{booking.id}}</dd>
                        <dt class="col-md-4">Date d'arrivée</dt>
                        <dd class="col-md-8">{{booking.startDate | date('d/m/Y')}}</dd>
                        <dt class="col-md-4">Date de sortie</dt>
                        <dd class="col-md-8">{{booking.endDate | date('d/m/Y')}}</dd>
                        <dt class="col-md-4">Nombre de nuits </dt>
                        <dd class="col-md-8">{{booking.duration}}</dd>
                        <dt class="col-md-4">Montannt Total</dt>
                        <dd class="col-md-8">{{booking.amount}}</dd>
                        <dt class="col-md-4">Commentaire </dt>
                        <dd class="col-md-8">{{booking.comment | default("aucun commentaire")}}</dd>
                    </dl>

                    <div class="row">
                        <h2> Votre Hôte</h2>
                        <div clas="col-3">
                            <img src="{{author.picture}}" class="avatar avatar-medium">
                        </div>

                        <div class="col-9">
                            <h4>
                                <a href="{{path('user_show',{'slug':author.slug}) }}">{{author.fullName}} </a>
                            </h4>
                            <span class="badge badge-primary">{{author.ads | length}} Annonces </span>
                        </div>
                </div>

                <div class="alert alert-light">
                    <h2  class="alert-heading"> Votre avis compte (après séjour) </h2>
                    {% if date() > date(booking.endDate %}
                        {% set comment= booking.ad.commentFromUser(app.user) %}
                        {% if comment is not null %}
                            <blockquote>
                                {{comment.content}}
                            </blockquote>
                            <strong> Note: </strong>
                            
                            {% include 'shared/rating.html.twig'%}#}

                        {% else %}
                            {{form_start(form)}}
                            {{form_widget(form)}}
                            <button type="submit" class="btn btn-success"> Confirmer! </button>
                            {{form_end(form)}}
                        {% endif %}
                    {% else %}
                        <p> Revenez plus tard pour pouvoir commenter </p>
                    {% endif %}
                </div>
            </div>

            <div class="col">
                <div class="alert alert-light">
                    <h2 class="alert-heading"> Votre Hébergement</h2>
                    </h2>
                    <h4>
                        <a href= "{{path('ads_show',{'slug':ad.slug})}}">{{ad.title}}</a>
                    </h4>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

logiciels/xampp/htdocs/symfony4/my_project_name/templates/booking/index_book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver l'annonce:{{ad.title}}{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css"/>
{% endblock %}

{% block body %}

    <div class="container">
        <h1> Réserver l'annonce: {{ad.title}}</h1>
        <p> Vous êtes sur le point de réserver le bien de <strong>{{ad.author.fullName}}</strong> dites nous tout</p>
        {{form_start(form)}}
        <div class="alert alert-light">
            <h2> Commencez par nous dire quelles sont vos dates</h2>
            <div class="row">
                <div class="col">
                    {{form_row(form.startDate)}}
                </div>
                <div class="col">
                    {{form_row(form.endDate)}}
                </div>
            </div>
            <h4> Montant du séjour; <span id="amount">...</span> &euros;</h4>
            <span id="days">0</span> nuits à {{ad.price}} / nuit

            <h2> Do you have any comment</h2>
            {{form_row(form.comment)}}
        </div>

        <h2> Vous avez terminé!</h2>
        <p> Vacances de rêve?</p>
        <button type="submit" class="btn btn-success"> Je reserve</button>
        {{form_end(form)}}

        
    </div>

{% endblock %}
{#lancement de datepicker#}
{% block javascript %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.az.min.js"></script>
    <script>
    /*
        $(document).ready(function(){
            $('#booking_startDate,#booking_endDate').datepicker({
                format:'dd/mm/yyyy',
                
                datesDisabled:[
                    {% for day in ad.notAvailableDays %}
                        "{{day.format('d/m/Y')}}",
                    {% endfor %}
                ],
                startDate=new Date()


            });

            $('#booking_endDate,#booking_startDate').on('change',calculateAmount);
                
        })
        */
        function calculAmount(){
            const endDate=new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/),'$3-$2-$1'));
            const startDate=new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/),'$3-$2-$1'));

            if(startDate && endDate && startDate < endDate){
                const day_time=24*60*60*1000;

                const interval=endDate.getTime()-startDate.getTime();
                const days=interval/day_time;
                const amount=days * {{ad.price}};

                $('#days').text(days);
                $('#amount').text(amount.toLocalString('fr-Fr'));
            }
        }
    </script>
{% endblock %}