logiciels/xampp/htdocs/symfony4/my_project_name/src/Entity/Ad.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use App\Repository\AdRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdRepository::class)
 * @ORM\HasLifecycleCallbacks
 */
class Ad
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="ad", orphanRemoval=true)
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }
    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return void
     */

    public function initializeSlug()
    {
        if(empty($this->slug))
        {
            $slugify=new Slugify();
            $this->slug=$slugify->slugify($this->title);
        }
    }

    /**
     * Permet de récupérer le commentaire s'un utilisateur par rapport à une annonce
     * @param User $user
     * @return comment|null
     */

    public function getCommentFromAuthor(User $user){
        foreach($this->comments as $comment){
            if($comment->getAuthor===$user){
                return $comment;
            }
            return null;

        }
    }

    /**
     *
     * 
     */

    public function getAvgRating(){
        //calcul de ka somme des notations
        $sum=array_reduce($this->comments->toArray(),function($total,$comment){
            return $total+$comment->getRating();
        },0);

        if(count($this->comments >0)){
            $moyenne=$sum/count($this->comments);
            return (int)$moyenne;
        }
        return 0;
    }

    /**
     * Permer d'obtenir un tableau des jours qui ne sont pas dispo pour cette annonce
     * @return array Un tableau d'objets DateTime des jours d'occupation
     */
    public function getNotAvailableDays(){
        $notAvailableDays=[];

        foreach($this->bookings as $booking){
            $resultat=range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60
            );
            $days=array_map(function($dayTimestamp){
                return new \DateTime(date('Y-m-d',$dayTimestamp));
            },$resultat);
            $notAvailableDays=array_merge($notAvailableDays,$days);
        }

        return $notAvailableDays;

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

logiciels/xampp/htdocs/symfony4/my_project_name/src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * //@ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 * fields={"email"},
 * message="Un autre utilisateur a cet email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un email valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $picture;

    /**
     * @Assert\EqualTo(propertyPath="hash",message="Fausse confirmation de mot de passe")
     */

    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Ad::class, mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author", orphanRemoval=true)
     */
    private $comments;
  

    public function getFullName(){
        return "{$this->firstName} {$this->lastName}";
    }

   

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return void
     */

    public function initializeSlug()
    {
        if(empty($this->slug))
        {
            $slugify=new Slugify();
            $this->slug=$slugify->slugify($this->firstName.''.$this->lastName);
        }
    }
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    //UserInterface methods 

    public function getRoles(){
        //$roles=$this->userRoles->toArray();
        //dump($roles);

        $roles = $this->userRoles->map(function($role){
            return $role->getTitle();
        })->toArray();
        $roles[]='ROLE_USER';
        //dump($roles)
        return $roles;
    }

    public function getPassword(){
        return $this->hash;
    }

    public function getSalt(){

    }

    public function getUsername(){
        return $this->email;
    }

    public function eraseCredentials(){

    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->removeElement($userRole)) {
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

    

logiciels/xampp/htdocs/symfony4/my_project_name/src/Form/AdType.php
<?php

namespace App\Form;

use App\Entity\Ad;
use App\Form\ImageType;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class AdType extends AbstractType
{

    private function getConf($label,$placeholder)
    {
        return [
            'label'=>$label,
            'attr'=>[
                'placeholder'=>$placeholder
            ]
            ];
    }
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title',TextType::class,[
                'label'=>'Titre',
                'attr'=>['placeholder'=>"Tapez un super titre pour votre annonce!"]
            ])
            ->add('slug',TextType::class,$this->getConf("adresse Web","Tapez l'adresse web"))
            ->add('price')
            ->add('introduction')
            ->add('content')
            ->add('coverImage')
            ->add('rooms')
            ->add(
                'images',
                CollectionType::class,[
                    'entry_type'=>ImageType::class,
                    'allow_add'=>true,
                    'allow_delete'=>true
                ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ad::class,
        ]);
    }
}

logiciels/xampp/htdocs/symfony4/my_project_name/templates/ad/_ad.html.twig
<div class="container">
    <h1> Voici les annonces de nos hôtes</h1>

    <div class="row">
        {% for ad in ads %}
            {% set url= path('ads_show',{'slug':ad.slug}) %}
            <div class="col-md-4">
                <div class="card bg-light mb-3>
                    <div class="card-header text-center">
                        {{ad.rooms}} chambres, <strong>{{ad.price}}&euro;/ nuit</strong> <br>
                        <small> Pas encore noté</small>
                    </div>
                    <a href="{{url}}">
                        <img src="{{ad.CoverImage}}" alt="Image de l'appartement" style="height:200px; width:100%;display:block">
                    </a>
                    <div class="card-body">
                        <h4 class="card-title">
                            <a href="{{url}}">
                                {{ad.title}}
                            </a>
                        </h4>
                        <p class="card-text">
                            {{ad.introduction}}
                        </p>
                        <a href="{{url}}" class="btn btn-secondary"> En savoir Plus ! </a>
                    </div>

                </div>
            </div>
            
        
        {% endfor %}
    </div>
</div>

logiciels/xampp/htdocs/symfony4/my_project_name/templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos magnifiques annonces{% endblock %}

{% block body %}
<div class="container">
    <h1> Voici les annonces de nos hôtes</h1>

    <div class="row">
        {% for ad in ads %}
            {% set url= path('ad_show',{'slug':ad.slug}) %}
            <div class="col-md-4">
                <div class="card bg-light mb-3>
                    <div class="card-header text-center">
                        {{ad.rooms}} chambres, <strong>{{ad.price}}&euro;/ nuit</strong> <br>
                        <small> Pas encore noté</small>
                    </div>
                    <a href={{url}}>
                        <img src="{{ad.CoverImage}}" alt="Image de lappartement" style="height:200px; width:100%;display:block">
                    </a>
                    
                    <div class="card-body">
                        <h4 class="card-title">
                            <a href={{url}}>
                                {{ad.title}}
                            </a>
                        </h4>
                        <p class="card-text">
                            {{ad.introduction}}
                        </p>
                        <a href={{url}} class="btn btn-secondary"> En savoir Plus ! </a>
                    </div>

                </div>
            </div>
            
        
        {% endfor %}
    </div>
</div>
{% endblock %}

logiciels/xampp/htdocs/symfony4/my_project_name/templates/ad/new.html.twig
{% extends 'base.html.twig' %}
{% form_theme form _self %}
{% block title %} Creation d'une annonce {% endblock %}
{# % form_theme form _self %} 
{% form_theme form 'foundation_5_layout.html.twig' %}
#}

{%block body %}
    <div class="container">
        <h1> Créer une nouvelle annonce</h1>
        {# this form theme will be applied only to the form of this template #}
        
        
        {{form_start(form)}}
        
        {{form_widget(form)}}
        <button type="submit" class="btn btn-primary">Créer la nouvelle annonce</button>
        {{form_end(form)}}
        
        {#
        {{form(form)}}
        {{form_widget(form)}}
        #}
    </div>
{% endblock %}

{% block _ad_images_widget %}
    <p>Ici, vous pourvez ajouter votre image </p>
    {{form_widget(form)}}

    <input type="hidden" id="widgets-counter" value="0">

    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">Ajouter une image</button>
    </div>
{% endblock %}

{% block ad_images_entry_row %}
    {{form_widget(form)}}
{% endblock %}

{% block _ad_images_entry_widget %}
    <div class="form-group" id="block_{{id}}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{form_widget(form.url)}}
                        {{form_errors(form.url)}}
                    </div>

                    div class="col">
                        {{form_widget(form.caption)}}
                        {{form_errors(form.caption)}}
                    </div>
                </div>
            </div>
        <div class="col-2">
            <button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger"> X </button>
        </div>
            

        </div>
    </div>
{% endblock %}

{% block javascripts %}
<script>
    $('#add-image').click(function(){
        //const index=+$('#ad_images div.form-group').length;
        const index=$('#widgets-counter').val();
        //je récupère les prototypes des entrées
        const tmpl=$('#ad_images').data('prototype').replace(/__name__/g,index);{# le g pour dire on répète plusieurs fois#}
        //console.log(tmpl);
        $('#ad_images').append(tmpl);
        $('#widgets-counter').val(index+1);
        // je gère le boutton supprimer
        handleDelete();
    });

    function handleDelete(){
        $('button[data-action="delete"]').click(function(){
            const target=this.dataset.target;
            //console.log(target);
            $(target).remove();
        })
    }
    handleDelete();
</script>
{% endblock %}

logiciels/xampp/htdocs/symfony4/my_project_name/templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ad.title}}
{%endblock%}

{% block body %}

<div class="add-title" style="background-image:url({{ad.CoverImage}})">
    <div class="container">
        <h1>{{ad.title}}</h1>
        <p>{{ad.introduction}}</p>
        <p class="h2>
            <strong>{{ad.rooms}} chambres</strong> pour <strong>{{ad.price}} & euro;</strong> par nuit
        </p>
        <a href="{{path('booking_create',{'slug':ad.slug}) }}" class="btn btn-primary">Réserver</a>

        {% if app.user and app.user==ad.author %}
            <a href="{{path('ads_edit',{'slug':ad.slug})}}" class="btn btn-secondary"> Modifier l'annonce</a>
            <a href="{{path('ads_delete',{'slug':ad.slug})}}" class="btn btn-danger" onclick="return confirm(`En etes-vous sur`)"> Supprimer l'annonce</a>
        {% endif %}

    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-8 mb-3">
            {{ad.content | raw}}


            <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                <ol class="carousel-indicators">
                    {% for image in ad.images %}
                        <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{loop.index0}}" 
                        {% if loop.first %} class="active"> {% endif%} </li>

                    {% endfor %}
                </ol>
                <div class="carousel-inner">
                    {% for image in ad.images %}
                        <div class="carousel-item {% if loop.first %}active{% endif%}">
                        
                            <img src="{{image.url}}" class="d-block w-100" alt="...">

                            <div class="carousel-caption d-none d-md-block">
                                <h5>{{ad.title}}</h5>
                                <p>image.caption</p>
                            </div>
                        </div>
                    {% endfor %}
                    
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </a>
            </div>
            
            {# les commentaire et notes des annonces #}
            <hr>

            {% if ad.comments | length>0 %}
                <h2 class="mb-3">Commentaires de nos voyageurs</h2>
                
                <div class="alert alert-info">
                    <h4 class="alert-heading text-center">
                        <div class="row align-item-center">
                            <div class="col">
                                Note globale donnée par nos voyageurs <br>
                                <small> Cette moyenne est </small>
                                
                            </div>
                                {#{% include "shared/rating.html.twig" with {"rating": {{ad.avgRating}} %}
                                <span class="rating">
                                    {% for i in 1..5 %}
                                        {% if i <= comment.rating %}
                                         <i class="fas fa-star"></i>
                                        {% else %}
                                            <i class="far fa-star"></i>

                                        {% endif %}
                                    {% endfor %}

                                <span>
                                #}
                            <div class="col">
                            
                            </div>
                        </div>
                    </h4>
                </div>
                
                {% for comment in ad.comments %}
                    <div class="bg-light rounded mb-3 py-3 px-3">
                        <strong>{{comment.author.fullName}} a dit:
                        <blockquote>
                            {{comment.content}}
                        </blockquote>
                        Note donnée par: <strong>{{comment.author.fullName}} </strong> est: 
                        {{comment.rating}}
                      
                        {#{% include 'shared/rating.html.twig' with {'rating':comment.rating %}#}
                        <span class="rating">
                            {% for i in 1..5 %}
                                {% if i <= comment.rating %}
                                    <i class="fas fa-star"></i>
                                {% else %}
                                    <i class="far fa-star"></i>

                                {% endif %}
                            {% endfor %}

                        <span>

                        <span class="rating">
                            {% for i in 1..5 %}
                                {% if i <=comment.rating %}
                                    <i class="fas fa-star"></i>
                                {% else %}
                                    <i class="far fa-star"></i>

                                {% endif %}
                            {% endfor %}

                        <span>  
                    </div>

                {% endfor %}

            {% else %}
                <h2>Cette annonce na pas encore de commentaires </h2>
            {% endif %}
            
        </div>

{#
        <div class="col">
            {% set a=ad.author %}
            <div class="row mb-3 align-items-center">
                <div class="col-3">
                    <a href="{{path('user_show',{'slug':a.slug})}}">
                        <img src="{{ad.picture}}">
                    </a>
                </div>
                <div class="col">
                    <a href="{{path('user_show',{'slug':a.slug})}}">
                        <h3>{{a.fullName}}</h3>
                    </a>
                    <span class="badge badge-primary">{{a.ads | length }} annonces</span>
                </div>
            </div>
            <p> Ceci est un paragraphe de présentation Ceci est un paragraphe de présentation Ceci est un paragraphe de présentation
            </p> 
        </div>
           
        <div class="col">
            <div class="row">
                <div class="col-4">
                    <img src="http://placehold.it/64x64" alt="Avatar de Joseph">
                </div>

                <div class="col">   
                    <h3>Joseph Dupont</h3>
                    <span class="badge badge-primary">3 annonces</span>
                </div>
            </div>
        </div>
        
        <div class="row align-items-center">
            <div class="col-3 text-center">
                <img src="{{user.picture}}" class="avatar mb-3" alt="Avatar de {{user.fullName}}">
                <br>
                <div class="col-9">
                    <h1>{{user.fullName}}</h1>

                    {% if user is same as(app.user) %}

                        <div class="mt-3">
                            <a href= "{{path('account_profile')}}" class="btn btn-primary mr-2 mb-2"> Modifier mes informations </a>
                            <a href= "{{path('account_pwd')}}" class="btn btn-primary mr-2 mb-2"> Modifier mon mot de passe </a>
                        </div>
                </div>
            </div>
            {{user.description | raw }}
            <hr>
            <h2> les annonces de {{user.fullName}}</h2>

            {% if user.ads | length > 0 %}
            {% else %}

            {% endif %}
        </div>
        #}

    </div>

</div>


{% endblock%}